# Default values for vote.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


httpServicePort: &defaultServicePort 80
tag: &defaultTag latest
namespace: default
clusterIP: 10.10.0.10
clusterDomain: nip.io
registry: &defaultRegistry local-registry:5002

services:
  ecserver: 
    imageName: ecserver # without registry-host and tag
    imageTag: *defaultTag
    serviceName: "ecserver"
    servicePort: *defaultServicePort
