apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: ecserver
  namespace: {{ .Values.namespace }}
  labels:
    domain: k8s-gateway.nginx.org
spec:
  gatewayClassName: nginx
  listeners:
  - name: http
    hostname: "{{ .Values.services.ecserver.serviceName }}.{{ .Values.clusterIP }}.{{ .Values.clusterDomain }}"
    port: 80
    protocol: HTTP
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ .Values.services.ecserver.serviceName }}
  namespace: {{ .Values.namespace }}
spec:
  parentRefs:
  - name: ecserver
  hostnames:
  - "{{ .Values.services.ecserver.serviceName }}.{{ .Values.clusterIP }}.{{ .Values.clusterDomain }}"
  rules:
  - backendRefs:
    - name: {{ .Values.services.ecserver.serviceName }}
      port: 80
    matches:
    - headers:
      - type: Exact
        name: env
        value: {{ .Values.services.ecserver.serviceName }}