
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: hello
  namespace: {{ .Values.namespace }}
spec:
  parentRefs:
  - name: gateway
    namespace: default
    sectionName: http
  hostnames:
  - "{{ .Values.services.ecserver.serviceName }}.{{ .Values.clusterIP }}.{{ .Values.clusterDomain }}"
  rules:
  - matches:
    - headers:
      - type: Exact
        name: env
        value: {{ .Values.namespace }}
    backendRefs:
    - name: hello
      port: 80