
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: ecserver
  namespace: {{ .Values.namespace }}
spec:
  parentRefs:
  - name: gateway
    namespace: default
    sectionName: http
  hostnames:
  - "{{ .Values.services.ecserver.serviceName }}.{{ .Values.clusterIP }}.{{ .Values.clusterDomain }}"
  - "testnow-on-demand-mayank-3845.ec.13.232.139.118.nip.io"
  rules:
  - matches:
    - headers:
      - type: Exact
        name: env
        value: {{ .Values.namespace }}
    backendRefs:
    - name: {{ .Values.services.ecserver.serviceName }}
      port: {{ .Values.httpServicePort }}
  - backendRefs:
    - name: ecserver
      port: 80
      namespace: default

---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: {{ .Values.namespace }}
  namespace: default
spec:
  from:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    namespace: {{ .Values.namespace }}
  to:
  - group: ""
    kind: Service